import globals from "globals";
import pluginJs from "@eslint/js";

export default [
  pluginJs.configs.recommended,

  {languageOptions: {globals: globals.browser}},

  {
    ignores: ["**/static/js/marked.js", "**/static/ruffle/**"],
  },

  {
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
      "indent": ["error", 2],
      "linebreak-style": ["error", "unix"],
      "quotes": ["error", "backtick"],
      "no-console": "error",
      "no-multi-spaces": "error",
      "no-multiple-empty-lines": ["error", {"max": 1}],
      "object-shorthand": ["error", "always"],
      "semi": ["error", "never"],
      "no-else-return": "error",
      "padded-blocks": ["error", "never"],
      "no-lonely-if": "error",
      "eqeqeq": ["error", "always"],
      "curly": ["error", "all"],
      "brace-style": ["error", "stroustrup", {"allowSingleLine": true}],
      "no-var": "error",
      "arrow-spacing": ["error", {"before": true, "after": true}],
      "space-in-parens": ["error", "never"],
      "object-curly-spacing": ["error", "never"],
      "prefer-object-spread": "error",
      "no-eval": "error",
      "no-useless-escape": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      "keyword-spacing": "error",
      "space-infix-ops": "error",
      "comma-spacing": "error",
      "comma-dangle": ["error", "always-multiline"],
      "no-extra-parens": ["error", "all", {
        "nestedBinaryExpressions": false,
        "enforceForArrowConditionals": false,
        "returnAssign": false
      }],
      "padding-line-between-statements": [
        "error",
        { "blankLine": "always", "prev": "block-like", "next": "*" }
      ],
      "func-call-spacing": ["error", "never"],
      "space-before-function-paren": ["error", {
        "anonymous": "never",
        "named": "never",
        "asyncArrow": "always"
      }],
      "no-mixed-operators": [
        "error",
        {
          "groups": [
            ["&&", "||"],
            ["&&", "==="],
            ["&&", "!=="],
            ["&&", "=="],
            ["&&", "!="],
            ["&&", ">"],
            ["&&", ">="],
            ["&&", "<"],
            ["&&", "<="],
            ["||", "==="],
            ["||", "!=="],
            ["||", "=="],
            ["||", "!="],
            ["||", ">"],
            ["||", ">="],
            ["||", "<"],
            ["||", "<="],
            ["==", "!=", "===", "!=="],
            ["in", "instanceof"],
          ],
          "allowSamePrecedence": true
        }
      ]
    },
    languageOptions: {
      globals: {
        App: "readonly",
        DOM: "readonly",
        Msg: "readonly",
        Utilz: "readonly",
        Croppie: "readonly",
        Handlebars: "readonly",
        jdenticon: "readonly",
        Dropzone: "readonly",
        io: "readonly",
        Twitch: "readonly",
        SC: "readonly",
        YT: "readonly",
        onYouTubeIframeAPIReady: "writable",
        ColorLib: "readonly",
        NeedContext: "readonly",
        dateFormat: "readonly",
        browser: "readonly",
        module: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        AColorPicker: "readonly",
        process: "readonly",
        require: "readonly",
        marked: "readonly",
        Popmsg: "readonly",
        Promptext: "readonly",
        Confirmbox: "readonly",
        Tooltip: "readonly",
        ace: "readonly",
        Utils: "readonly",
        Curls: "readonly",
        Items: "readonly",
        Container: "readonly",
        Update: "readonly",
        Combo: "readonly",
        Infobar: "readonly",
        Windows: "readonly",
        Select: "readonly",
        Controls: "readonly",
        Dates: "readonly",
        Colors: "readonly",
        Intro: "readonly",
        Move: "readonly",
        Sort: "readonly",
        Picker: "readonly",
        Status: "readonly",
        List: "readonly",
        Block: "readonly",
        Menu: "readonly",
        Filter: "readonly",
        Footer: "readonly",
        Change: "readonly",
        Drag: "readonly",
        Font: "readonly",
        Border: "readonly",
        More: "readonly",
      }
    }
  }
]
