DROP TABLE IF EXISTS curls;

CREATE TABLE curls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    curl TEXT NOT NULL,
    passkey TEXT NOT NULL,
    content TEXT NOT NULL
);