DROP TABLE IF EXISTS curls;

CREATE TABLE curls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP NOT NULL,
    curl TEXT NOT NULL UNIQUE,
    key TEXT NOT NULL,
    status TEXT NOT NULL
);