DROP TABLE IF EXISTS curls;

CREATE TABLE curls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    curl TEXT NOT NULL,
    key TEXT NOT NULL,
    text TEXT NOT NULL
);